### ISSUE TITLE
Allow volunteers to subscribe to the Green Software Playbooks project

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-playbooks#1]
# Context 

We want to allow GSF volunteers to subscribe to the project.

# Actions

- [x] Setup Google Group - "green-software-playbooks@"
- [x] Add project to [project subscription list](https://greensoftware.foundation/subscribe/)

**Comment by seanmcilroy29** [comment]
@russelltrow - green-software-playbooks@greensoftware.foundation has been created, and you've been assigned as the owner.

**Comment by seanmcilroy29** [comment]
@russelltrow - [Subscription](https://greensoftware.foundation/subscribe/) form has been updated with [green-software-playbooks@greensoftware.foundation](mailto:green-software-playbooks@greensoftware.foundation). Test completed, and anyone who subscribes to the list is now added to the G-Group member list.

**Comment by russelltrow** [comment]
Amazing thank you @seanmcilroy29 !
