### ISSUE TITLE
2024-08-01 - Green Software Playbooks agenda

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-playbooks#12]
## Date
2024-08-01 - 14:00 UTC - See the time in your timezone https://everytimezone.com

## Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

### Previous Meeting

-

## Agenda

- [ ] Convene & Roll Call
- [ ] Review the agenda and suggest new agenda points
- [ ] Review suggestions in discussion here: https://github.com/Green-Software-Foundation/green-software-playbooks/discussions/10 
- [ ] Settle on a role of focus
- [ ] AOB, Q&A & Adjourn

## Any Other Business

- [ ] Co-chair role still open

**Comment by russelltrow** [comment]
Attended

**Comment by moin-oss** [comment]
Attended

**Comment by f-mellinghoff** [comment]
attended

**Comment by KarthikeyanKumar17** [comment]
Attended

**Comment by moin-oss** [comment]
Current list of roles

- Data Science and AI / Machine learning
- Data Engineering
- DevOps / SRE
- Scrum Master / PO / Project Manager
- Architect / Principal Engineer
- Software Engineer
  - Mobile app developer
  - Front-end developer
  - UX / UI Design
  - Back-end developer
- End User
  - Can split into clients and others

**Comment by moin-oss** [comment]
Start with Data Engineering

Some initial ideas
- Minimizing duplicate data
- Building efficient pipelines
- Scheduling pipelines and run times
- Building good data models
- Batch processing
- Right-sizing clusters
- Shutting down VMs not in use

**Comment by moin-oss** [comment]
@moin-oss to create a new discussion topic on data engineering projects and practices

**Comment by moin-oss** [comment]
Proposed category changes [here](https://github.com/Green-Software-Foundation/green-software-playbooks/issues/13)
New discussion topic opened [here](https://github.com/Green-Software-Foundation/green-software-playbooks/discussions/15)
