### ISSUE TITLE
Logo for Green Software Playbooks project

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-playbooks#2]
# Context

We need a logo for the project!

# Actions

- [x] Design logo
- [x] Add to [website project listing](https://greensoftware.foundation/projects)
- [x] Update repository with logo

**Comment by Jenya-design** [comment]
@russelltrow please let me know when you need the logo ready
Can I have a link to project page or any other description? Can't find on the website
Thank s

**Comment by russelltrow** [comment]
Hey @Jenya-design you can find more information on the project in the [README](https://github.com/Green-Software-Foundation/green-software-playbooks/blob/dev/README.md).

If we could have the logo ready for mid May that would be wonderful.

**Comment by Jenya-design** [comment]
Thank you @russelltrow, sure, I'll send you the update next week for review
Could you please add this issue to Design project? I can't do that for some reason

**Comment by Jenya-design** [comment]
@russelltrow @moin-oss  please check two options for the logo and let me know what you think

![Image](https://github.com/Green-Software-Foundation/green-software-playbooks/assets/69306070/fe007577-bf64-4180-9848-317877e6d5c7)

**Comment by russelltrow** [comment]
Number 2 please @Jenya-design

**Comment by Jenya-design** [comment]
@russelltrow please check files for the logo and icon:

- [svg format](https://drive.google.com/drive/folders/1FTRIVn_utPARSWCTjL3q8PXvB4D3DoPA?usp=drive_link)
- [png format](https://drive.google.com/drive/folders/1IQR7CoS7GWOk-JYt16zkpBibHFZ08wFP?usp=drive_link)
- [all files](https://drive.google.com/drive/folders/1jV8r1sl0ysinb020EJuvEFpvPms6kgi0?usp=drive_link)
