### ISSUE TITLE
Organise a project kick-off

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-playbooks#5]
# Context

We would like to hold a project kick-off with all interested parties:

* Take place on 20 June 2024
* Held virtually on Zoom

All interested parties should subscribe to the project to be automatically added to the calendar invite: https://greensoftware.foundation/subscribe

The meeting will be documented on the project wiki: 

# Resources

* https://docs.google.com/document/d/199kr2ZusP47vDjTVqn1FFRvueF3gX9vNMPAVUptmpK4/edit#heading=h.b6ygb76ogd5y

# Actions

- [x] @moin-oss @russelltrow agree a Date & Time
- [x] @russelltrow create calendar invite
- [x] @moin-oss define initial participant list
- [x] @moin-oss @russelltrow build agenda
- [x] @moin-oss announce meeting to CWG

**Comment by russelltrow** [comment]
Schedule for 1 month from today at 14:00 UTC

**Comment by russelltrow** [comment]
@moin-oss would it be possible to have the kick-off meeting at 14:30 or 15:00 UTC on the 20 June? 

There is a GSF Steering Committee call 13:30 - 14:30 UTC on that day.

**Comment by moin-oss** [comment]
@russelltrow Depending on how long the meeting should be, we could try to aim for 14:30 UTC that day.  I've got a meeting at 15:00 UTC, so can't do that time.  If you think the meeting will go over 30 minutes, then we should probably reschedule.

**Comment by russelltrow** [comment]
Kick-off run on Wednesday 26th June 2024.
